import "../styles/globals.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";

const futurePT = localFont({
  src: [
    {
      path: "../assets/fonts/FuturePT/FuturaPT-Light.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../assets/fonts/FuturePT/FuturaPT-Book.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/FuturePT/FuturaPT-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/FuturePT/FuturaPT-Demi.woff",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={futurePT.className}>{children}</body>
    </html>
  );
}
